version: '3.8'

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: static-website
    ports:
      - "80:80"  # Expose the website on port 80
    volumes:
      - ./html:/var/www/html  # Bind mount the html folder
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf  # Custom Nginx config
    networks:
      - web-network
    depends_on:
      - php
      - apache

  apache:
    image: httpd:latest
    container_name: apache-server
    ports:
      - "8080:80"  # Expose Apache on port 8080
    volumes:
      - ./html:/var/www/html  # Bind mount the html folder
      - ./apache/httpd.conf:/usr/local/apache2/conf/httpd.conf  # Custom Apache config
    networks:
      - web-network
    depends_on:
      - php

  php:
    image: php:7.4-fpm
    container_name: php-server
    volumes:
      - ./html:/var/www/html
    ports:
      - "9000:9000"  # Expose PHP-FPM port
    networks:
      - web-network

networks:
  web-network:
    driver: bridge
